### ISSUE TITLE
Use winrt::single_threaded_observable_vector(std::vector<IInspectable>) instead of winrt::make<observable_vector<IInspectable>>()

### ISSUE THREAD

**Issue by dPJinjo** [Microsoft/Windows-appsample-photo-editor#1]
In the MainPage.cpp file in the MainPage constructor the code initializes m_photos using winrt::make<observable_vector<IInspectable>>(). This could instead be winrt::single_threaded_observable_vector(std::vector<IInspectable>). Would doing so eliminate the need to define an implementation of observable_vector in the app? Would it be possible to eliminate ObservableVector.h entirely?

Also, why is the item type IInspectable rather than Photo? Is it because XAML doesn't understand the type Photo? Could you add the [Windows.UI.Xaml.Data.Bindable] attribute to the Photo.idl to force the XamlCompiler to emit type information about Photo for usage in XAML?

**Comment by JoshuaPartlow** [comment]
Hi! Thanks very much for your interest in the sample and in c++ /WinRT. 

At present, the sample is using Windows 10 SDK Build 17134, which did not have single_threaded_observable_vector. You are definitely right though that using a Preview Build of the SDK it could be used instead, eliminating the need for ObservableVector. In a future update of the sample that's a change we intend to make. 

For the XAML binding itself, you do need to use an IVector of IInspectable. The XAML process will QueryInterface the IInspectable for various interfaces to determine things like whether the collection is observable and make calls to the implementations of those interfaces. If you were to bind to an IVector of Photo, you would get an exception from the XAML process. 

Does that help with your questions?

**Comment by bmitchell287** [comment]
Closing this issue, please re-open if you want to discuss further. Thanks for trying it out.
