### ISSUE TITLE
Win2D version conflict?

### ISSUE THREAD

**Issue by BeErikk** [Microsoft/Windows-appsample-photo-editor#2]
I get:
`PhotoEditor.vcxproj(175,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Win2D.uwp.1.21.0\build\native\Win2D.uwp.targets.`

So I cloned Win2D and built it successfully according to the Win2D instructions. I still get the message above. My Win2D version is currently **1.23.0**.

If it is a version conflict, what is the proper way to solve it?

thanks

**Comment by JoshuaPartlow** [comment]
Hi, hopefully we can help get this sorted out. Have you verified the NuGet package shows as installed from the Nuget Package Manager within Visual Studio and is also showing as a reference in the VS project? If it is, could you try uninstalling the package from the Package Manager UI and then re-adding it? If it doesn't, please try adding it from the Package Manager UI. The following topic has guidance on doing those steps [NuGet Package Manager UI](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui). Please let me know if that corrects the issue.

**Comment by BeErikk** [comment]
Thanks
Yes, Win2D is visible in the Nuget Package Manager and I tried to update the project, which succeeded in a sense. I ended up with both the original and the new build. I eventually manually deleted the two lines specifying the old original Win2D version in the project vcxproj file. The project builds fine now.
